import getAllUsers from "@/lib/getAllUsers";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Users",
  description: "Generated by create next app",
};

export default async function UsersPage() {
  const usersData: Promise<User[]> = getAllUsers();
  const users = await usersData;

  const content = (
    <section>
      <h2>
        <Link href="/">Back To Home</Link>
      </h2>
      <br />

      {users.map((user) => {
        return (
          <>
            <p>{user.id}</p>
            <Link href={`/users/${user.id}`}>{user.name}</Link>
            <br />
          </>
        );
      })}
    </section>
  );

  return content;
}
